"""
VHAS Dual-System API Server
"""

import asyncio
import json
import os
from pathlib import Path
from typing import AsyncGenerator, Dict, Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

import sys
project_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(project_root))

from ai.dual_system.neuro_symbolic_router import orchestrate_workflow_step

app = FastAPI(title="VHAS Production Backend", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class OrchestrateRequest(BaseModel):
    nl_command: str

def _sse_data(payload: Dict[str, Any]) -> str:
    return f"data: {json.dumps(payload, ensure_ascii=False)}\n\n"

def _chunk_text(text: str, chunk_size: int = 100) -> list[str]:
    return [text[i : i + chunk_size] for i in range(0, len(text), chunk_size)]

@app.post("/api/orchestrate")
async def orchestrate(request: OrchestrateRequest) -> StreamingResponse:
    nl_command = request.nl_command.strip()

    async def event_generator() -> AsyncGenerator[str, None]:
        try:
            # 1. Call the router (load GNN and run System 2 when confidence is low)
            result = await orchestrate_workflow_step(
                patient_context=nl_command,
                graph_history={}, 
                tau_threshold=0.85
            )

            # 2. Handle the router's returned result
            final_action = result.get("action")
            if not final_action:
                raise ValueError("No action was generated by the dual-system.")

            # 3. Stream the result to the frontend in chunks
            serialized_payload = json.dumps(final_action, ensure_ascii=False)
            chunks = _chunk_text(serialized_payload)
            
            for chunk in chunks:
                yield _sse_data({"type": "delta", "text": chunk})
                await asyncio.sleep(0.02) 

            yield _sse_data({"type": "done"})

        except Exception as exc:
            yield _sse_data({"type": "error", "message": str(exc)})

    return StreamingResponse(event_generator(), media_type="text/event-stream")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=False)